version: '2'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    ports:
      - "9010:8080"
    volumes:
      - jenkins_data/:/var/jenkins_home
  sonarqube:
    container_name: sonarqube
    image: sonarqube:7.8-community
    ports:
      - "9011:9000"

volumes:
  jenkins_data:
  sonar_data:
