version: '2'
services:
  back:
    build:
      context: high-way-to-devops
      dockerfile: Dockerfile
    image: back
    container_name: back
    ports:
      - "8070:8080"
    links:
      - postgres:bdd
  front:
    build:
      context: high-way-to-devops-front
      dockerfile: Dockerfile
    container_name: front
    image: front
    links:
      - back:back-api
    ports:
      - "8072:80"
    volumes:
      - ./high-way-to-devops-front/conf:/etc/nginx/conf.d/
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin

volumes:
  jenkins_data:
  sonar_data:
