apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mehdi
  namespace: default
subjects:
  - kind: User
    name: mehdi
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: list-pods
  apiGroup: rbac.authorization.k8s.io
