apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      application: back
  template:
    metadata:
      name: back
      labels:
        application: back
        type: back-end
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'example'
        vault.hashicorp.com/agent-inject-secret-credentials.txt: 'kv/devops'
    spec:
      serviceAccountName: vault-auth
      initContainers:
      - args:
          - agent
          - -config=/etc/vault/application.properties
          - -log-level=debug
        env:
          - name: VAULT_ADDR
            value: 'http://52.73.153.8:8200'
        image: vault
        name: vault-agent
        volumeMounts:
          - mountPath: /etc/vault
            name: config
          - mountPath: /etc/secrets
            name: shared-data
      containers:
        - name: back
          ports:
            - containerPort: 8080
              name: default-port
          image: mchekini/back:{{ .Values.imageVersion }}
          imagePullPolicy: IfNotPresent
          env:
             - name: VAULT_ADDR
               value: 'http://52.73.153.8:8200'
             - name: VAULT_TOKEN
               value: root
          command:
            - java
            - -jar
            - /opt/high-way-to-devops.jar
            - --spring.config.location=file:///configuration/application.properties
          volumeMounts:
            - mountPath: /configuration
              name: back-config
      volumes:
        - name: back-config
          configMap:
            name: back-config-map
