apiVersion: v1
kind: ConfigMap
metadata:
  name: back-config-map
data:
  application.properties: |
    #DataSource settings
    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "example"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }
    spring.datasource.url=jdbc:postgresql://bdd-svc:5432/postgres
    spring.datasource.username={{ .Data.data.login }}
    spring.datasource.password={{ .Data.data.password }}
    spring.datasource.driver-class-name=org.postgresql.Driver


    #jpa settings
    spring.jpa.database=postgresql
    spring.jpa.show-sql=false
    spring.jpa.hibernate.ddl-auto=create
    spring.jpa.hibernate.naming.strategy=org.hibernate.cfg.ImprovedNamingStrategy
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

    #Flyway
    spring.flyway.user=postgres
    spring.flyway.password=admin
    spring.flyway.schemas=public
    spring.flyway.url=jdbc:postgresql://bdd-svc:5432/postgres
    spring.flyway.locations=classpath:db/migration


